development:
  clients:
    default:
      uri: mongodb+srv://Fed1k@admin:fed1k2002@cluster0.f1egczk.mongodb.net/searchDb?retryWrites=true&w=majority
      options:
        # Add any development-specific options here if needed

test:
  clients:
    default:
      database: searchDb
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: mongodb+srv://Fed1k@admin:fed1k2002@cluster0.f1egczk.mongodb.net/searchDb?retryWrites=true&w=majority
      options:
        # Add any production-specific options here if needed
